[build]
  base = "podhub-frontend-rolla"
  command = "cd podhub-frontend-rolla && npm run build"
  publish = "podhub-frontend-rolla/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"